services:
  - type: web
    name: motract-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build && ls -R dist
    startCommand: cd backend && ls -la && npx drizzle-kit push && node dist/main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: motract-db
          property: connectionString
      - key: PORT
        value: 10000

databases:
  - name: motract-db
    plan: free
    databaseName: motract
    user: motract_user
